function keyPressed(){
    if(key=="w"){
        if(legalMove(screen.main[screen.position[0]-1][screen.position[1]])&&
        legalMove(screen.main[screen.position[0]-2][screen.position[1]])&&
        screen.active[screen.position[0]-1][screen.position[1]]==0&&
        screen.active[screen.position[0]-2][screen.position[1]]==0){
            screen.active[screen.position[0]-1][screen.position[1]]=1
            screen.active[screen.position[0]-2][screen.position[1]]=1
            screen.position[0]-=2
        }
    }
    if(key=="s"&&screen.position[0]<screen.main.length-2){
        if(legalMove(screen.main[screen.position[0]+1][screen.position[1]])&&
        legalMove(screen.main[screen.position[0]+2][screen.position[1]])&&
        screen.active[screen.position[0]+1][screen.position[1]]==0&&
        screen.active[screen.position[0]+2][screen.position[1]]==0){
            screen.active[screen.position[0]+1][screen.position[1]]=1
            screen.active[screen.position[0]+2][screen.position[1]]=1
            screen.position[0]+=2
        }
    }
    if(key=="a"){
        if(legalMove(screen.main[screen.position[0]][screen.position[1]-1])&&
        legalMove(screen.main[screen.position[0]][screen.position[1]-2])&&
        screen.active[screen.position[0]][screen.position[1]-1]==0&&
        screen.active[screen.position[0]][screen.position[1]-2]==0){
            screen.active[screen.position[0]][screen.position[1]-1]=1
            screen.active[screen.position[0]][screen.position[1]-2]=1
            screen.position[1]-=2
        }
    }
    if(key=="d"){
        if(legalMove(screen.main[screen.position[0]][screen.position[1]+1])&&
        legalMove(screen.main[screen.position[0]][screen.position[1]+2])&&
        screen.active[screen.position[0]][screen.position[1]+1]==0&&
        screen.active[screen.position[0]][screen.position[1]+2]==0){
            screen.active[screen.position[0]][screen.position[1]+1]=1
            screen.active[screen.position[0]][screen.position[1]+2]=1
            screen.position[1]+=2
        }
    }
    if(keyCode==BACKSPACE&&game.enter.trigger){
        game.enter.trigger=false;
    }
    if(keyCode==ENTER){
        if(screen.main[screen.position[0]][screen.position[1]]=='o'){
            entities.screens[game.enter.select].active=true
            screen.complete=true
        }
    }
}