function keyPressed(){
    if((key=="w"||keyCode==UP_ARROW)&&screen.position[0]>0){
        if(legalMove(screen.main[screen.position[0]-1][screen.position[1]])&&
        legalMove(screen.main[screen.position[0]-2][screen.position[1]])&&
        screen.active[screen.position[0]-1][screen.position[1]]==0&&
        screen.active[screen.position[0]-2][screen.position[1]]==0){
            screen.active[screen.position[0]-1][screen.position[1]]=1
            screen.active[screen.position[0]-2][screen.position[1]]=1
            screen.position[0]-=2
        }
        else if(legalMove(screen.main[screen.position[0]-1][screen.position[1]])&&
        legalMove(screen.main[screen.position[0]-2][screen.position[1]])&&
        screen.active[screen.position[0]-1][screen.position[1]]==1&&
        screen.active[screen.position[0]-2][screen.position[1]]==1){
            screen.active[screen.position[0]][screen.position[1]]=0
            screen.active[screen.position[0]-1][screen.position[1]]=0
            screen.position[0]-=2
        }
    }
    if((key=="s"||keyCode==DOWN_ARROW)&&screen.position[0]<screen.main.length-2){
        if(legalMove(screen.main[screen.position[0]+1][screen.position[1]])&&
        legalMove(screen.main[screen.position[0]+2][screen.position[1]])&&
        screen.active[screen.position[0]+1][screen.position[1]]==0&&
        screen.active[screen.position[0]+2][screen.position[1]]==0){
            screen.active[screen.position[0]+1][screen.position[1]]=1
            screen.active[screen.position[0]+2][screen.position[1]]=1
            screen.position[0]+=2
        }
        else if(legalMove(screen.main[screen.position[0]+1][screen.position[1]])&&
        legalMove(screen.main[screen.position[0]+1][screen.position[1]])&&
        screen.active[screen.position[0]+1][screen.position[1]]==1&&
        screen.active[screen.position[0]+2][screen.position[1]]==1){
            screen.active[screen.position[0]][screen.position[1]]=0
            screen.active[screen.position[0]+1][screen.position[1]]=0
            screen.position[0]+=2
        }
    }
    if((key=="a"||keyCode==LEFT_ARROW)&&screen.position[1]>0){
        if(legalMove(screen.main[screen.position[0]][screen.position[1]-1])&&
        legalMove(screen.main[screen.position[0]][screen.position[1]-2])&&
        screen.active[screen.position[0]][screen.position[1]-1]==0&&
        screen.active[screen.position[0]][screen.position[1]-2]==0){
            screen.active[screen.position[0]][screen.position[1]-1]=1
            screen.active[screen.position[0]][screen.position[1]-2]=1
            screen.position[1]-=2
        }
        else if(legalMove(screen.main[screen.position[0]][screen.position[1]-1])&&
        legalMove(screen.main[screen.position[0]][screen.position[1]-2])&&
        screen.active[screen.position[0]][screen.position[1]-1]==1&&
        screen.active[screen.position[0]][screen.position[1]-2]==1){
            screen.active[screen.position[0]][screen.position[1]]=0
            screen.active[screen.position[0]][screen.position[1]-1]=0
            screen.position[1]-=2
        }
    }
    if((key=="d"||keyCode==RIGHT_ARROW)&&screen.position[1]<screen.main[0].length-2){
        if(legalMove(screen.main[screen.position[0]][screen.position[1]+1])&&
        legalMove(screen.main[screen.position[0]][screen.position[1]+2])&&
        screen.active[screen.position[0]][screen.position[1]+1]==0&&
        screen.active[screen.position[0]][screen.position[1]+2]==0){
            screen.active[screen.position[0]][screen.position[1]+1]=1
            screen.active[screen.position[0]][screen.position[1]+2]=1
            screen.position[1]+=2
        }
        else if(legalMove(screen.main[screen.position[0]][screen.position[1]+1])&&
        legalMove(screen.main[screen.position[0]][screen.position[1]+2])&&
        screen.active[screen.position[0]][screen.position[1]+1]==1&&
        screen.active[screen.position[0]][screen.position[1]+2]==1){
            screen.active[screen.position[0]][screen.position[1]]=0
            screen.active[screen.position[0]][screen.position[1]+1]=0
            screen.position[1]+=2
        }
    }
    if(keyCode==SHIFT&&game.enter.trigger){
        game.enter.trigger=false
        entities.screens[game.enter.select].details.active=screen.active
        entities.screens[game.enter.select].details.fade=screen.fade
        entities.screens[game.enter.select].image.clear()
        entities.screens[game.enter.select].genImage()
    }
    if(keyCode==ENTER&&screen.main[screen.position[0]][screen.position[1]]=='o'){
        screen.complete=true
        for(a=0,la=screen.main.length;a<la;a++){
			for(b=0,lb=screen.main[a].length;b<lb;b++){
				switch(screen.main[a][b]){
					case '*':
                        if(screen.active[a][b]==0){
                            screen.complete=false
                        }
                    break
                }
            }
        }
        if(screen.complete){
            entities.screens[game.enter.select].complete=true
        }
    }
    if(keyCode==BACKSPACE){
        resetScreen()
    }
}