class wall extends entity{
    constructor(layer,x,y,type,width,height){
        super(layer,x,y)
        this.type=type
        this.width=width
        this.height=height
        this.collide=[entities.players]
        if(this.type<=0){
            this.screen = screens[-this.type]
            this.image = createGraphics(this.screen[0].length*20,this.screen.length*20)
            for(e=0,le=this.screen.length;e<le;e++){
                for(f=0,lf=this.screen[e].length;f<lf;f++){
                    switch(this.screen[e][f]){
                        case '.': case 'O': case 'o':
                            this.image.stroke(0)
                            this.image.strokeWeight(5)
                            if(e<this.screen.length-1&&(this.screen[e+1][f]=='.'||this.screen[e+1][f]=='O'||this.screen[e+1][f]=='o')){
                                this.image.line(10+f*20,10+e*20,10+f*20,30+e*20)
                            }
                            if(f<this.screen[e].length-1&&(this.screen[e][f+1]=='.'||this.screen[e][f+1]=='O'||this.screen[e][f+1]=='o')){
                                this.image.line(10+f*20,10+e*20,30+f*20,10+e*20)
                            }
                            if(this.screen[e][f]=='O'){
                                this.image.strokeWeight(15)
                                this.image.point(10+f*20,10+e*20)
                            }
                            if(this.screen[e][f]=='o'){
                                this.image.strokeWeight(10)
                                this.image.point(10+f*20,10+e*20)
                            }
                        break
                    }
                }
            }
        }
        switch(this.type){
            case 1:
                this.ellipse=[]
                this.control=[]
                for(e=0,le=this.width/80;e<le;e++){
                    this.ellipse.push([])
                    this.control.push([])
                    for(f=0,lf=this.height/80;f<lf;f++){
                        this.ellipse[e].push([])
                        this.control[e].push(random(0,1))
                        for(g=0;g<4;g++){
                            this.ellipse[e][f].push([random(15,25),random(15,25),random(60,70)])
                        }
                    }
                }
            break
        }
    }
    display(){
        this.layer.noStroke()
        this.layer.translate(this.position.x,this.position.y)
        if(this.type<=0){
            this.layer.stroke(40)
            this.layer.strokeWeight(3)
            this.layer.fill(255,100,150)
            this.layer.rect(0,0,60,60,3)
            this.layer.image(this.image,-25,-25,50,50)
        }
        switch(this.type){
            case 1:
                this.layer.fill(255,50,100)
                for(e=0,le=this.ellipse.length;e<le;e++){
                    for(f=0,lf=this.ellipse[e].length;f<lf;f++){
                        this.layer.translate(-this.width/2+40+e*80,-this.height/2+40+f*80)
                        this.layer.rotate(this.control[e][f]*360)
                        for(g=0,lg=this.ellipse[e][f].length;g<lg;g++){
                            this.layer.ellipse(this.ellipse[e][f][g][0]*((g%2)*2-1),this.ellipse[e][f][g][1]*(floor(g/2)*2-1),this.ellipse[e][f][g][2],this.ellipse[e][f][g][2])
                        }
                        this.layer.rotate(this.control[e][f]*-360)
                        this.layer.translate(this.width/2-40-e*80,this.height/2-40-f*80)
                    }
                }
            break
        }
        if(dev.box){
            this.layer.noFill()
            this.layer.stroke(0,255,0)
            this.layer.strokeWeight(3)
            this.layer.rect(0,0,this.width,this.height)
        }
        this.layer.translate(-this.position.x,-this.position.y)
    }
    update(){
        for(e=0,le=this.collide.length;e<le;e++){
            for(f=0,lf=this.collide[e].length;f<lf;f++){
                if(circleInsideBox(this,this.collide[e][f])){
					this.collide[e][f].position.x=circleCollideBox(this,this.collide[e][f]).x
					this.collide[e][f].position.y=circleCollideBox(this,this.collide[e][d]).y
                    this.collide[e][f].speed=0
				}
            }
        }
    }
}